name: Scalping XAUUSD

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  kirim-sinyal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install yfinance ta requests
      - name: Jalankan script scalping
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python xauusd.py
